### ISSUE TITLE
Test counter has bug 

### ISSUE THREAD

**Issue by Azerima** [vfarid/cf-ip-scanner#13]
سلام آقا وحید 
وقت بخیر 
اول از همه بابت تمامی زحماتتان برای تمامی آموزش ها و درست کردن اسکریپت هایی که بتواند به ما کمک کند تو این شرایط سخت 
از شما سپاس گذارم 
مشکل : 
این نسخه اخر پیدا کردن ایپی از طریق لینک سایت باگ داره 
لینک استفاده شده : https://vfarid.github.io/cf-ip-scanner/

https://user-images.githubusercontent.com/91154409/229341920-da7ca732-ac50-4af5-abf6-0e65b19d2f41.mp4

همین طور که تو فیلم مشاهده میکنید خیلی از حجم RAM/CPU به طرز عجیبی میگیره 
و اصلا ایپی رو اسکن نمیکنه 
نسخه قبلی بینهایت . بینهایت فوق العاده بود ممنون میشم اونو برگردونید 
vpn خاموش بود 
چیزی دانلود نمیشد 
کروم  
کیلیر هیستوری شد 
کیلیر کش شد 
اینترنت خانه 
اگه اطلاعات دیگری نیاز بود بفرمایید بفرستم 
اون پینگ تایم هم ثابت مثل همیشه بود نمیدونم مورد نیاز میشه یا نه دیگه گفتم بزارم 
سپاس

**Comment by Azerima** [comment]
لینک که استفاده کردم
https://vfarid.github.io/cf-ip-scanner/

**Comment by vfarid** [comment]
این نسخه رنج آی‌پی های به مراتب وسیع‌تری داره و به همین دلیل زمان بیشتری طول میکشه. نسخه‌ی قبلی هم روی کتابخونه هست. میتونید فورک کنید و روی یک کتابخونه‌ی جدید فعالش کنید یا حتی دانلود کنید و روی گوشی/سیستم خودتون بازش کنید.
