### ISSUE TITLE
پیدا نکردن آی پی تمیز بعد از آپدیت اخیر

### ISSUE THREAD

**Issue by iamomid1997** [vfarid/cf-ip-scanner#21]
با درود و وقت بخیر
بعد از آپدیت اخیر، اسکنر کار نمیکنه و آی پی تمیز پیدا نمیکنه
من با نت همراه اول و تنظیمات دیفالت اسکنر، اسکن رو انجام دادم
لطفا توضیحات فارسی راجع به بخش های اضافه شده بعد از آپدیت اخیر هم اضافه کنید
https://vfarid.github.io/cf-ip-scanner/

**Comment by vfarid** [comment]
مشکل از اعمال محدودیت‌های جدید بود که در سوشال نوشته بودم. الان میتونید کد مستر رو دانلود و روی سیستم خودتون از طریق باز کردن فایل index.html با بروزر اجرا کنید و اسکن رو با پروتکل http انجام بدید.
