### ISSUE TITLE
قسمت پورت مشکل داره

### ISSUE THREAD

**Issue by Afarhud** [vfarid/cf-ip-scanner#23]
سلام و عرض ادب ، دوست عزیز وقتی روی کادر پورت کلیک میکنم صفحه کلید بالا نمیاد که عددی وارد کنم با چند تا مرورگر چک کردم نشد . سپاس از زحمات شما

**Comment by sarahtuska** [comment]
اجازه اجرای جاوا اسکریپت به مرورگرت بده . و بعدش پورت ها ظاهر می شه و میتونی انتخاب کنی کدام پورت

**Comment by Afarhud** [comment]
جاوااسکریپتم اکیه ولی باز هم پورت ها خالی هستش و صفحه کلید غیر فعاله

**Comment by sarahtuska** [comment]
مشکل از مرورگرت هست . عوض کن و مثلا از firfox  یا  brave  یا چیز دیگه ای استفاده کن. مشکلت حل می شه
