### ISSUE TITLE
مشکل عدم ذخیره کردن ایپی های اسکن شده

### ISSUE THREAD

**Issue by omid-j-d** [vfarid/cf-ip-scanner#24]
سلام
من ایپی هارو از طریق پروتکل https که اسکن میکنم 
ایپی های پیدا شده رو ذخیره نمیکنه و اگر مشخص کرده باشیم ۱۰ ایپی بیشتر اسکن نکنه تا بینهایت این کار رو انجام میده

**Comment by AlexAnorak** [comment]
same here

**Comment by Jakallll** [comment]
اسکنر متوقف نمیشه

**Comment by Jakallll** [comment]
اسکنر متوقف نمیشه

**Comment by alikharazm1** [comment]
سلام آقا فرید عزیز برای بنده هم همینطوره . آی پی پیدا میکنه سبز میشه ولی لیست نمیکنه و متوقف هم نمیشه

**Comment by vfarid** [comment]
این‌مشکل عدم ذخیره نیست، ایراد در نمایشه، اسکنر تحت وب با محدودیت‌های اخیری که ایجاد شده نمیتونه آی‌پی پیدا کنه، تو کانال تلگرامم نوشتم که میتونید سورسش رو روی لوکال اجرا کنید با پروتکل http. اینجا فعلا کاربردی نداره.
من unpublish نکردم چون شاید در کشورهای دیگه کاربرد داشته باشه.
