### ISSUE TITLE
Cf-ip-worker 

### ISSUE THREAD

**Issue by Lorenzo19877** [vfarid/cf-ip-scanner#7]

**Comment by Lorenzo19877** [comment]
addEventListener(

    "fetch",event => {

        let url=new URL(event.request.url);

        url.hostname="your domin";

        url.pathname="/";

        let request=new Request(url,event.request);

        event. respondWith(

            fetch(request)

        )

    }

)

**Comment by vfarid** [comment]
Not related to this code
